package com.example.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// The id is the Firestore document ID (not a locally autogenerated number),
// so the same driver has the same identity across every device once synced.
@Entity(tableName = "drivers")
data class DriverEntity(
    @PrimaryKey val id: String = "",
    val name: String,
    val phone: String,
    val vehicle: String, // e.g. "Bicycle", "Motorbike", "Car"
    val isAvailable: Boolean = true
)
